apiVersion: v1
kind: Pod
metadata:
  name: ebpf
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: ebpf
    image: ubuntu:22.04
    command:
      - "sleep"
      - "infinity"
    securityContext:
      capabilities:
        add: ["SYS_BPF"]
  hostNetwork: true
  dnsPolicy: Default
