apiVersion: v1
kind: Pod
metadata:
  name: shell-demo
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: shell-demo
    image: ubuntu
    command:
      - "sleep"
      - "infinity"
  hostNetwork: true
  dnsPolicy: Default
